{% set ambertools_package = 'AmberTools' %}
{% set ambertools_version = 16.20 %}
{% set ambertools_fn = "AmberTools16.tar.bz2" %}
{% set ambertools_url = "https://dl.dropboxusercontent.com/u/5494759/AmberTools16.tar.bz2" %}

package:
  name: {{ ambertools_package }}
  version: {{ ambertools_version }}

source:
  fn : {{ ambertools_fn }}
  url : {{ ambertools_url }}
  # path: ../

build:
  number: 1

requirements:
  build:
    - python
    - zlib
    - bzip2
  run:
    - python
    - zlib
    - bzip2
    - numpy

test:
  commands:
    - cpptraj --defines
    - tleap -h
    - sqm -h
    - antechamber -h
    - parmchk2 -h

about:
    home: https://ambermd.org
    license: GNU General Public License (GPL)
    summary: AmberTools is a set of programs for biomolecular simulation and analysis.
