# {% set ambertools_package = 'ambertools' %}
{% set ambertools_package = 'ambermini_test' %}
{% set ambertools_version = "16.20" %}
{% set ambertools_fn = "AmberTools16.tar.bz2" %}

# Please update your name and other info if you maintain or update this recipe
{% set ambertools_url = "http://ambermd.org/cgi-bin/AmberTools16-get.pl?Name=HaiNguyen&Institution=Rutgers&City=NewBrunswicks&State=NJ&Country=USA" %}

package:
  name: {{ ambertools_package }}
  version: {{ ambertools_version }}

source:
  fn : {{ ambertools_fn }}
  url : {{ ambertools_url }}

  # Use local path: specify local path here and comment above lines (fn, url)
  # path: ../

build:
  number: 1

requirements:
  build:
    - zlib
    - bzip2
    # - python
  run:
    - zlib
    - bzip2
    # - python
    # - numpy

test:
  commands:
    - cpptraj --defines
    - tleap -h
    - sqm -h
    - antechamber -h
    - parmchk2 -h

about:
    home: https://ambermd.org
    license: GNU General Public License (GPL)
    summary: AmberTools is a set of programs for biomolecular simulation and analysis.
