os: osx
language: c
install:
    # - source build.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew tap homebrew/science;
          brew update;
          brew install gfortran;
      fi
    - source scripts/install_miniconda.sh
    - conda build recipe
script: echo "hello"
after_success:
    - echo "hello"
notifications:
  email: false
