os: osx
language: c
install:
    # - source build.sh
    - source scripts/install_miniconda_travis.sh
    - conda build recipe
script: echo "hello"
after_success:
    - echo "hello"
notifications:
  email: false
