os:
- linux
language: c
sudo: required
services:
- docker
install: sh scripts/travis-build.sh
script: echo "hello"
after_success:
    - docker ps -a
    - docker images
    - docker run my_image ipython
notifications:
  email: false
