# Use GCC
sudo: true
language: cpp
matrix:
  include:
   - { os: osx, env: AMBER_BUILD_TASK=ambermini }
   - { os: osx, env: AMBER_BUILD_TASK=ambertools }
   - { os: linux, env: AMBER_BUILD_TASK=ambermini }
   - { os: linux, env: AMBER_BUILD_TASK=ambertools }
install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew tap homebrew/science;
          brew update;
          brew install homebrew/versions/gcc6;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo apt-get install -y csh;
      fi
    - source scripts/install_miniconda.sh
    - conda build recipe
script: echo "hello"
after_success:
    - echo "hello"
notifications:
  email: false
