os:
- linux
language: c
sudo: required
services:
- docker
install: sh scripts/travis-build.sh
script: echo "hello"
after_success:
    - docker ps -a
    - docker images
    - eval $(docker-machine env)
    - source scripts/travis-test.sh
notifications:
  email: false
